version: '3'
services:
  edgedelta:
    image: gcr.io/edgedelta/agent:latest
    network_mode: host
    restart: always
    privileged: true
    labels:
      io.balena.features.balena-socket: '1'
network_mode: host
      
