version: "2"
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
      volumes:
        - data:/data
    restart: unless-stopped
    labels:
      - io.balena.features.balena-socket: 1
volumes:
  data:
