version: '2.1'
services:
  edgedelta:
    image: gcr.io/edgedelta/agent:balena-test
    privileged: true
    restart: always
    environment:
      ED_API_KEY: "00000000-0000-0000-0000-000000000000"
    labels:
      io.balena.features.balena-socket: '1'

