version: '2'
services:
  edgedelta:
    image: gcr.io/edgedelta/agent:latest
    restart: always
    environment:
      ED_API_KEY: "c61ddba5-2026-47b3-9620-b69d57264d31"
    labels:
      io.balena.features.balena-socket: '1'
     
